### ISSUE TITLE
'libproj-dev' and 'libgeos++-dev' should be installed with conda

### ISSUE THREAD

**Issue by johtoblan** [metno/solr-indexer#1]

**Comment by mortenwh** [comment]
`conda install -c conda-forge cartopy`?

**Comment by johtoblan** [comment]
Looks like it yes.

**Comment by magnarem** [comment]
Added some more dependencies to requirements.txt.
I can now run pip install . in this repo locally inside a python venv, without errors.

Please test this, to double check that this is reproducable

**Comment by mortenwh** [comment]
It seems to work locally but difficult to validate without a test suite. I've added two simple tests, and tried to push a new version of dmci but the installation still fails there.
