### ISSUE TITLE
Better handeling parsing dates.

### ISSUE THREAD

**Issue by magnarem** [metno/solr-indexer#13]
The parsing of dates from MMD and conversion to SolR ISO date-format is not robust enough.

We have occurances when the parsing will fail because a `Z` is just added to the datestring if missing. This can make the dateutil.pareser to throw an exception (dateutil.parser._parser.ParserError: Unknown string format:)  which create a 500-server error in `DMCI` and indexdata will not index the document.

We need some better tests and logic for parsing dates.

This will have to apply for the following mmd-fields.

last_metadata_update_datetime
temporal_extent_start_date
temproal_extent_end_date
publication_date

**Comment by johtoblan** [comment]
https://github.com/metno/solr-indexer/blob/40890a084fd4ef46178761844663aff8a46ace63/solrindexer/indexdata.py#L210

Seems to only be last_metadata_update? Atleast searching for uses of parser.parse

**Comment by magnarem** [comment]
This problem is  now handled, and changes pushed to master

**Comment by magnarem** [comment]
Merged branch ```fix-issue-13``` to ```master```. Closing this issue.
