### ISSUE TITLE
Still need better handling of date parsing in MMD4Solr:check_mmd

### ISSUE THREAD

**Issue by magnarem** [metno/solr-indexer#16]
In the tosolr()-function of MMD4Solr, we now have good date parsing, but still in the check_mmd()-function, it is still some bad code when handling checking of dates.
Some modifications have to be done here to make it better and test a bit.

**Comment by mortenwh** [comment]
Some unit tests would be useful in the long run, so I would recommend to gradually look into that..

**Comment by magnarem** [comment]
closing this
