### ISSUE TITLE
Merge in changes from steingod/solrindexing master branch

### ISSUE THREAD

**Issue by magnarem** [metno/solr-indexer#2]
This repo are behind multiple commits compared with the repo [github.com/steingod/solrindexing . master ](https://github.com/steingod/solrindexing) master branch.

I will do a manual merging of changed code from [github.com/steingod/solrindexing - master ](https://github.com/steingod/solrindexing)  into [github.com/metno/solr-indexer](https://github.com/metno/solr-indexer)

**Comment by mortenwh** [comment]
Can this be closed?
